### ISSUE TITLE
Move audit related logic out of content-script.js

### ISSUE THREAD

**Issue by socsieng** [GoogleChromeLabs/form-troubleshooter#18]
`content-script.js` currently contains some audit related logic. Specifically, determining which attributes are/aren't invalid (`invalidAttributes` and `invalidLabelDescendants`).

Proposal:

Instead of checking for invalid attributes in `content-script.js`, add all relevant attributes and check for validity in `audit.js`. This will make it easier to also apply _fuzzy_ attribute matches and provide alternate suggestions.

**Comment by samdutton** [comment]
IIRC the problem here is getting access to the DOM — so some audits need to be done in the content script.

However, I don't like the way the code-concerns are mixed up, and I'm sure there are better ways to structure the work currently done in `content-script.js`. Maybe messaging `content-script.js` from `audit.js` to make requests relating to the DOM?

**Comment by socsieng** [comment]
FYI, I'm working on a pull request that includes the following:

- DOM traversal including `iframe` content (#12)
- Extracts audit related logic out of `content-script.js` and into `audit.js`

I hope to have a PR ready for you to review soon.

**Comment by socsieng** [comment]
#16 has been updated to include these changes.
