### ISSUE TITLE
Should autocomplete="off" be treated as a warning?

### ISSUE THREAD

**Issue by socsieng** [GoogleChromeLabs/form-troubleshooter#7]
Related to #2 around severity and whether or not warnings should be actionable.

Warning from a [Shopify store's](https://www.mollyjogger.com/) checkout page:

> Form fields should not use `autocomplete="off"`.
>Found form field(s) with autocomplete="off":
> - `<input autocomplete="off" class="field__input" id="checkout_reduction_code" name="checkout[reduction_code]" placeholder="Gift card or discount code">`
>   Setting `autocomplete="off"` does not disable autofill.

`autocomplete="off"` should be valid according to https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-off (despite browsers choosing to ignore it). Should this result in a warning?

**Comment by samdutton** [comment]
This is a warning (not an error) in the latest version of the extension.

I was in two minds about this.

`autocomplete="off"` is valid HTML, but browsers ignore it, so it never does what's intended. To my mind, that's enough to make it an error, but... many sites use it and it doesn't actively cause a problem.

I've updated the warning message to add a bit more detail.

**Comment by socsieng** [comment]
Based on the following comment: https://github.com/GoogleChromeLabs/form-troubleshooter/issues/2#issuecomment-884080214

> I think both warnings and errors should be actionable.

What is the ask for developers? Should they remove `autocomplete="off"` altogether? Or is this more informational?

**Comment by samdutton** [comment]
Just had some discussion with Dominic about this. I think I've been misunderstanding the way this works: I thought `autocomplete="off"` was disabled by browsers for all form fields, whereas from what I understand now, it sounds as if `autocomplete="off"` is only disabled for password and name-related fields (in Chrome at least). 

Waiting for confirmation. Sounds like I'll probably change the audit so it only checks for password and name-related fields. In that case, the advice would be to remove `autocomplete="off"`, since it will lead to unexpected results in most browsers (i.e. it doesn't work as intended). Anecdotally, I think some dev teams simply add this because they're told to.

**Comment by socsieng** [comment]
Sounds good.

> Anecdotally, I think some dev teams simply add this because they're told to.

FWIW, I've been in one of those teams.

**Comment by samdutton** [comment]
😏👍

**Comment by samdutton** [comment]
I've updated the warning message: try out the extension on [form-problems.glitch.me](https://form-problems.glitch.me/) to see this.
